<?php
namespace HSDCL\DteCl\Tests;

use HSDCL\DteCl\Sii\Base\JsonSource;

/**
 * @version 8/8/22 4:27 p. m.
 * @author  David Lopez <dleo.lopez@gmail.com>
 */
class JsonSourceTest extends \Orchestra\Testbench\TestCase
{
    /**
     * @author David Lopez <dleo.lopez@gmail.com>
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $dte = [
            'Encabezado' => [
                'IdDoc' => [
                    'TipoDTE' => 33,
                    'Folio' => 1,
                ],
                'Emisor' => [
                    'RUTEmisor' => '76192083-9',
                    'RznSoc' => 'SASCO SpA',
                    'GiroEmis' => 'Servicios integrales de informática',
                    'Acteco' => 726000,
                    'DirOrigen' => 'Santiago',
                    'CmnaOrigen' => 'Santiago',
                ],
                'Receptor' => [
                    'RUTRecep' => '60803000-K',
                    'RznSocRecep' => 'Servicio de Impuestos Internos',
                    'GiroRecep' => 'Gobierno',
                    'DirRecep' => 'Alonso Ovalle 680',
                    'CmnaRecep' => 'Santiago',
                ],
            ],
            'Detalle' => [
                [
                    'NmbItem' => 'Cajón AFECTO',
                    'QtyItem' => 123,
                    'PrcItem' => 923,
                ],
                [
                    'NmbItem' => 'Relleno AFECTO',
                    'QtyItem' => 53,
                    'PrcItem' => 1473,
                ],
            ],
        ];
        $this->cases = json_encode($dte);
    }

    /**
     * @author David Lopez <dleo.lopez@gmail.com>
     * @test
     **/
    public function canInstanciate()
    {
        $source = new JsonSource($this->cases);
        $this->assertInstanceOf(JsonSource::class, $source);
    }
}
