<?php

namespace HSDCL\DteCl\Tests\Feature;

use HSDCL\DteCl\Sii\Base\Dte;
use HSDCL\DteCl\Sii\Certification\CertificationBuilder;
use HSDCL\DteCl\Sii\Certification\ExemptCertificationBuilder;
use HSDCL\DteCl\Sii\Certification\FileSource;
use HSDCL\DteCl\Sii\Certification\BasicCertificationBuilder;
use HSDCL\DteCl\Util\Configuration;
use HSDCL\DteCl\Tests\TestCase;
use sasco\LibreDTE\FirmaElectronica;
use sasco\LibreDTE\Sii\Folios;

/**
 * Class ExampleTest
 * @package HSDCL\DteCl\Tests
 * @author David Lopez <dleo.lopez@gmail.com>
 */
class BasicCertificationBuilderTest extends TestCase
{
    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var FirmaElectronica
     */
    protected $firma;

    /**
     * @var Folios
     */
    protected $folios;

    /**
     * @var BasicCertificationBuilder
     */
    protected $certification;

    /**
     * @author David Lopez <dlopez@hsd.cl>
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $dotenv = \Dotenv\Dotenv::createImmutable(__DIR__ . '/../..');
        $dotenv->load();
        $emisor = [
            'RUTEmisor'  => env('RUTEmisor'),
            'RznSoc'     => env('RznSoc'),
            'GiroEmis'   => env('GiroEmis'),
            'Acteco'     => env('Acteco'),
            'DirOrigen'  => env('DirOrigen'),
            'CmnaOrigen' => env('CmnaOrigen'),
        ];

        $receptor = [
            'RUTRecep'    => env('RUTRecep'),    #'81515100-3',
            'RznSocRecep' => env('RznSocRecep'), #'SELIM DABED SPA.',
            'GiroRecep'   => env('GiroRecep'),   #'BARRACA Y FERRETERIA',
            'DirRecep'    => env('DirRecep'),    #'BENAVENTE 516',
            'CmnaRecep'   => env('CmnaRecep')    #'OVALLE',
        ];
        $this->config = Configuration::getInstance('folios-33', __DIR__ . '/../../resources/assets/xml/folios/33.xml');
        $this->firma = new FirmaElectronica(['file' => __DIR__ . '/../../resources/assets/certs/cert.pfx', 'pass' => env('FIRMA_PASS')]);
        $this->folios = [
            Dte::FACTURA_ELECTRONICA => new Folios(file_get_contents(Configuration::getInstance('folios-' . Dte::FACTURA_ELECTRONICA, __DIR__ . '/../../resources/assets/xml/folios/33.xml')->getFilename())),
            Dte::NOTA_DE_CREDITO_ELECTRONICA => new Folios(file_get_contents(Configuration::getInstance('folios-' . Dte::NOTA_DE_CREDITO_ELECTRONICA, __DIR__ . '/../../resources/assets/xml/folios/61.xml')->getFilename())),
            Dte::NOTA_DE_DEBITO_ELECTRONICA => new Folios(file_get_contents(Configuration::getInstance('folios-' . Dte::NOTA_DE_DEBITO_ELECTRONICA, __DIR__ . '/../../resources/assets/xml/folios/56.xml')->getFilename())),
        ];
        $this->certification = new BasicCertificationBuilder(
            $this->firma,
            new FileSource(__DIR__ . '/../../resources/assets/set_pruebas/001-basico.txt'),
            $this->folios,
            $emisor,
            $receptor
        );
    }

    /**
     * @test
     * @author David Lopez <dlopez@hsd.cl>
     */
    public function canInstance(): BasicCertificationBuilder
    {
        $this->assertInstanceOf(BasicCertificationBuilder::class, $this->certification);

        return $this->certification;
    }

    /**
     * @test
     * @depends canInstance
     * @param BasicCertificationBuilder $certification
     * @return BasicCertificationBuilder
     * @author  David Lopez <dlopez@hsd.cl>
     */
    public function canParse(BasicCertificationBuilder $certification): BasicCertificationBuilder
    {
        $startFolios = [
            Dte::FACTURA_ELECTRONICA => '6',
            Dte::NOTA_DE_CREDITO_ELECTRONICA => '6',
            Dte::NOTA_DE_DEBITO_ELECTRONICA => '6',
        ];
        $this->assertInstanceOf(BasicCertificationBuilder::class, $certification->parse($startFolios));

        return $certification;
    }

    /**
     * @test
     * @depends canParse
     * @param BasicCertificationBuilder $certification
     * @return BasicCertificationBuilder
     * @throws \HSDCL\DteCl\Util\Exception
     * @author David Lopez <dlopez@hsd.cl>
     */
    public function canStampAndSign(BasicCertificationBuilder $certification): BasicCertificationBuilder
    {
        $this->assertInstanceOf(BasicCertificationBuilder::class, $certification->setStampAndSign());

        return $certification;
    }

    /**
     * @test
     * @depends canStampAndSign
     * @param BasicCertificationBuilder $certification
     * @author  David Lopez <dlopez@hsd.cl>
     */
    public function canBuild(BasicCertificationBuilder $certification)
    {
        $output = 'file.xml';
        $this->assertGreaterThan(0, $certification->export($output));
    }

    /**
     * @test
     * @author David Lopez <dlopez@hsd.cl>
     */
    public function canExportToPdf()
    {
        $this->assertTrue(BasicCertificationBuilder::exportToPdf('/home/dlopez/Projects/Php/dte-cl/resources/assets/xml/set_basico/1.xml'));
    }
}
